// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2q80u5wlb3APs7hzxgn3jWU1d_S2vdI',
    appId: '1:672473578866:web:d41b886cb46eb630c1f1eb',
    messagingSenderId: '672473578866',
    projectId: 'tmdb-da4b0',
    authDomain: 'tmdb-da4b0.firebaseapp.com',
    storageBucket: 'tmdb-da4b0.appspot.com',
    measurementId: 'G-BXNPW5454F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqWOaQl06ht5DoFfepLlRv3ICR7Vvu_k',
    appId: '1:672473578866:android:acf4535d4441cc62c1f1eb',
    messagingSenderId: '672473578866',
    projectId: 'tmdb-da4b0',
    storageBucket: 'tmdb-da4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZpImdO_W3On2EGosCDydHRBKkKF0G4o',
    appId: '1:672473578866:ios:0854ca2b647c583dc1f1eb',
    messagingSenderId: '672473578866',
    projectId: 'tmdb-da4b0',
    storageBucket: 'tmdb-da4b0.appspot.com',
    iosClientId: '672473578866-bpq1fqhcp3ug6oe0h6egirc6ho2gg4td.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZpImdO_W3On2EGosCDydHRBKkKF0G4o',
    appId: '1:672473578866:ios:0854ca2b647c583dc1f1eb',
    messagingSenderId: '672473578866',
    projectId: 'tmdb-da4b0',
    storageBucket: 'tmdb-da4b0.appspot.com',
    iosClientId: '672473578866-bpq1fqhcp3ug6oe0h6egirc6ho2gg4td.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
